# Makefile to build class 'helloworld' for Pure Data.
# Needs Makefile.pdlibbuilder as helper makefile for platform-dependent build
# settings and rules.

# library name
# lib.name = grambilib~

# input source file (class name == source file basename)
gramulator~.class.sources = gramulator~.c

# all extra files to be included in binary distribution of the library
#
# include Makefile.pdlibbuilder from submodule directory 'pd-lib-builder'
include pd-lib-builder/Makefile.pdlibbuilder
